WeChat:
  appid:
  appsecret:
  template_id:
  openid:   #女朋友的openid 关注测试公众号后后台可查询
Task:
  cron: "0 0 7 * * ?"
Weather: #天气接口 tianqiapi.com
  appid:
  appsecret:
  city: 郑州
Date:
  anniversary:
    date: 2022/08/24
    isChineseCalendar: false #是否是农历
  boyBirthday:
    name: 小帅 #男生名字
    date: 2022/08/24
    isChineseCalendar: false #是否是农历
  girlBirthday:
    name: 小美 #女生名字
    date: 2022/08/24
    isChineseCalendar: false #是否是农历